"""
Hypothesis Model — KDM v4.0.0
==============================
Defines the Hypothesis dataclass representing a ranked competing root-cause
hypothesis generated by the Lead SRE Investigator Agent.
"""

from __future__ import annotations

from dataclasses import dataclass, field
import math
from typing import Any, Dict, List


@dataclass
class Hypothesis:
    """Diagnostic root-cause hypothesis formulated by Lead SRE Investigator.

    Represents a probable initial incident trigger correlated across
    specialist reports with assigned likelihood and supporting/contradicting evidence.
    """

    id: str
    description: str
    likelihood: float
    supporting_evidence: List[str]
    contradicting_evidence: List[str] = field(default_factory=list)

    def __post_init__(self) -> None:
        """Validate and clamp probability upon direct construction."""
        try:
            val = float(self.likelihood)
            is_valid = math.isfinite(val)
            self.likelihood = round(max(0.0, min(1.0, val)) if is_valid else 0.5, 4)
        except (ValueError, TypeError):
            self.likelihood = 0.5

    def to_dict(self) -> Dict[str, Any]:
        """Convert Hypothesis to a dictionary suitable for JSON serialization.

        :return: Standardized dictionary representation of the hypothesis.
        """
        return {
            "id": self.id,
            "description": self.description,
            "likelihood": round(float(self.likelihood), 4),
            "supporting_evidence": list(self.supporting_evidence),
            "contradicting_evidence": list(self.contradicting_evidence),
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> Hypothesis:
        """Create a Hypothesis instance from a dictionary with validation.

        :param data: Dictionary containing hypothesis fields.
        :return: Validated Hypothesis dataclass instance.
        """
        hyp_id = str(data.get("id") or "hyp-01")
        desc = str(data.get("description") or "Unknown incident trigger.")
        raw_prob = data.get("likelihood", 0.5)
        try:
            val = float(raw_prob)
            is_valid = math.isfinite(val)
            prob = max(0.0, min(1.0, val)) if is_valid else 0.5
        except (ValueError, TypeError):
            prob = 0.5

        supp = cls._sanitize_evidence_list(data.get("supporting_evidence"))
        contra = cls._sanitize_evidence_list(data.get("contradicting_evidence"))

        return cls(
            id=hyp_id,
            description=desc,
            likelihood=prob,
            supporting_evidence=supp,
            contradicting_evidence=contra,
        )

    @staticmethod
    def _sanitize_evidence_list(items: Any) -> List[str]:
        """Sanitize an evidence field into a clean list of non-empty strings.

        :param items: Raw evidence value (list, string, or None).
        :return: List of string evidence statements.
        """
        if isinstance(items, list):
            return [str(item).strip() for item in items if str(item).strip()]
        if items:
            cleaned = str(items).strip()
            return [cleaned] if cleaned else []
        return []
